Repository WildCodeSchool/orleans-202109-php-projet-apclo, pull requests merged in 2021-11, with the labels that each got.

#36 S1us07 display cat cards
  .tours/routing.tour
  database.sql
  public/assets/css/cards.css
  public/assets/css/cats.css
  public/assets/css/style.css
  public/assets/images/birth-day-logo.svg
  public/assets/images/cat-profil.svg
  public/assets/images/gender-logo.svg
  public/assets/images/paw.svg
  src/Controller/CatController.php
  src/Model/CatManager.php
  src/View/Cats/_card.html.twig
  src/View/Cats/index.html.twig
  src/routes.php
Labels: Reviewed

#42 S1us07 01 add relation tables
  .gitignore
  database.sql
  public/assets/css/cards.css
  public/assets/css/style.css
  src/Controller/CatController.php
  src/Model/CatManager.php
  src/View/Cats/_card.html.twig
  src/View/Cats/index.html.twig
Labels: Reviewed

#38 S01 us02
  .tours/simple-mvc.tour
  public/assets/css/banner.css
  public/assets/css/style.css
  public/assets/images/cat_banner.jpg
  src/View/Home/index.html.twig
  src/View/_banner.html.twig
Labels: Reviewed

#45 S1 US04 latest adopted
  src/Controller/HomeController.php
  src/Model/CatManager.php
  src/View/Home/_cardLatestAdopted.html.twig
  src/View/Home/_latestAdoptions.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed

#43 S1 US05 adopt
  src/Controller/HomeController.php
  src/Model/CatManager.php
  src/View/Home/_card.html.twig
  src/View/Home/_toAdopt.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed, Conflicts

#48 fixed apparence issues
  public/assets/css/banner.css
  src/View/Cats/_card.html.twig
Labels: Reviewed

#44 S01 us01 navbar
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/cat.svg
  public/assets/images/cathouse.svg
  public/assets/images/favicon.png
  public/assets/images/logo.png
  public/assets/images/mail.svg
  public/assets/images/paw.svg
  src/View/Item/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Conflicts

#50 saving last changes of dev branch on master
  public/assets/css/banner.css
  public/assets/css/footer.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/cat.svg
  public/assets/images/cathouse.svg
  public/assets/images/favicon.png
  public/assets/images/logo.png
  public/assets/images/logofacebook.svg
  public/assets/images/logofacebooksmall.svg
  public/assets/images/mail.svg
  public/assets/images/paw.svg
  src/Controller/HomeController.php
  src/Model/CatManager.php
  src/View/Cats/_card.html.twig
  src/View/Home/_card.html.twig
  src/View/Home/_toAdopt.html.twig
  src/View/Home/index.html.twig
  src/View/Item/_footer.html.twig
  src/View/Item/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#46 S1 us03
  public/assets/css/actuality.css
  public/assets/css/banner.css
  public/assets/css/style.css
  public/assets/images/cat_banner_actuality.jpg
  src/Controller/HomeController.php
  src/Model/ActualityManager.php
  src/View/Home/_actualityBanner.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed

#54 add ';' and delete padding in CSS in actuality-title h2
  public/assets/css/actuality.css
  public/assets/css/banner.css
Labels: Reviewed

#53 fix navbar (links, size...)
  src/View/Item/_navbar.html.twig
Labels: Reviewed, Conflicts

#51 S01 us10 display one catcard
  .gitignore
  database.sql
  public/assets/css/cards.css
  public/assets/css/large-card.css
  public/assets/css/style.css
  src/Controller/CatController.php
  src/Model/CatManager.php
  src/View/Cat/_large-card.html.twig
  src/View/Cat/show.html.twig
  src/View/Cats/_card.html.twig
  src/routes.php
Labels: Reviewed

#100 fixed display order of to adopt and latest adopted
  src/View/Home/index.html.twig
Labels: Reviewed

#99 S02US07-2-fix-card image size, responsive card, and displayed date changed
  public/assets/css/large-card.css
  src/Model/CatManager.php
  src/View/Cat/_large-card.html.twig
Labels: Reviewed

#98 S2 us07 3 fix spacing on cards
  public/assets/css/banner.css
  public/assets/css/cards.css
  src/View/Cats/_card.html.twig
  src/View/Home/_card.html.twig
  src/View/Home/_cardLatestAdopted.html.twig
Labels: Reviewed, Corrections done

#101 S02 us21
  database.sql
  public/assets/css/actuality.css
  public/assets/css/banner.css
  public/assets/images/separator.svg
  src/Controller/ActualityController.php
  src/View/Actualities/index.html.twig
  src/View/Home/_actualityBanner.html.twig
  src/View/Home/index.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#104 fixDatabase : cleaned, reorganised and added cats in database.sql
  database.sql
Labels: Reviewed

#106 S02US05-01_Add_photos_to_adopt_me
  src/View/Home/_cardToAdopt.html.twig
  src/View/Home/_toAdopt.html.twig
Labels: Review needed

#108 maybe this time la navbar va marcher : css .logo en nav .logo
  public/assets/css/navbar.css
  src/View/Item/_navbar.html.twig
Labels: Reviewed

#107 Fix s02 us05 01
  src/Model/CatManager.php
  src/View/Home/_cardToAdopt.html.twig
  src/View/Home/_toAdopt.html.twig
Labels: Reviewed

#109 Fix footer
  src/View/Item/_footer.html.twig
Labels: Reviewed

#110 syntaxe correction
  src/View/Item/_navbar.html.twig
Labels: Reviewed

#111 S02 us04 01 add photos to latest adopted
  src/Model/CatManager.php
  src/View/Home/_cardLatestAdopted.html.twig
Labels: Reviewed

#113 size issues fixed
  public/assets/css/cards.css
  src/View/Cats/_card.html.twig
  src/View/Home/_cardLatestAdopted.html.twig
  src/View/Home/_cardToAdopt.html.twig
Labels: Reviewed

#117 S02 us22 actuality admin
  public/assets/css/admin-actuality.css
  public/assets/css/style-admin.css
  public/assets/images/newspaper.svg
  public/assets/images/newspaper.tmp.svg
  src/Controller/AdminActualityController.php
  src/View/Admin/Actuality/index.html.twig
  src/View/layoutAdmin.html.twig
  src/routes.php
Labels: Reviewed

#123 fix : added border radius to cat images
  public/assets/css/cards.css
Labels: Reviewed

#126 Fixed actuality s02 us21
  public/assets/css/banner.css
  src/View/Actualities/index.html.twig
Labels: Reviewed

#129 Dev to Master c'est parti
  .gitignore
  database.sql
  public/assets/css/actuality.css
  public/assets/css/admin-actuality.css
  public/assets/css/banner.css
  public/assets/css/cards.css
  public/assets/css/large-card.css
  public/assets/css/navbar.css
  public/assets/css/style-admin.css
  public/assets/css/style.css
  public/assets/images/newspaper.svg
  public/assets/images/newspaper.tmp.svg
  public/assets/images/separator.svg
  src/Controller/ActualityController.php
  src/Controller/AdminActualityController.php
  src/Controller/CatController.php
  src/Model/CatManager.php
  src/View/Actualities/index.html.twig
  src/View/Admin/Actuality/index.html.twig
  src/View/Cat/_large-card.html.twig
  src/View/Cat/show.html.twig
  src/View/Cats/_card.html.twig
  src/View/Home/_actualityBanner.html.twig
  src/View/Home/_cardLatestAdopted.html.twig
  src/View/Home/_cardToAdopt.html.twig
  src/View/Home/_toAdopt.html.twig
  src/View/Home/index.html.twig
  src/View/Item/_footer.html.twig
  src/View/Item/_navbar.html.twig
  src/View/layoutAdmin.html.twig
  src/routes.php
Labels: Reviewed

#103 S02 us31 cat page
  public/assets/css/large-card.css
  src/Model/CatManager.php
  src/View/Cat/_cat-banner.html.twig
  src/View/Cat/_large-card.html.twig
  src/View/Cat/show.html.twig
Labels: Reviewed

#130 correction CSS date
  src/View/Actualities/index.html.twig
Labels: Reviewed

#119 S02 us23 addactuality
  public/assets/css/admin-actuality-form.css
  public/assets/css/admin-actuality.css
  public/assets/css/style-admin.css
  src/Controller/AdminActualityController.php
  src/Model/ActualityManager.php
  src/View/Admin/Actuality/_form.html.twig
  src/View/Admin/Actuality/add.html.twig
  src/View/Admin/Actuality/index.html.twig
  src/View/layoutAdmin.html.twig
  src/routes.php
Labels: Reviewed

#114 S02US12
  public/assets/css/asso.css
  public/assets/css/style.css
  public/assets/images/mail.svg
  src/Controller/AssociationController.php
  src/View/Association/index.html.twig
  src/View/Home/index.html.twig
  src/View/Item/_form.html.twig
  src/routes.php
Labels: Reviewed

#133 S02US15
  public/assets/css/form.css
  public/assets/images/separator2.svg
  src/Controller/AdminContactController.php
  src/Controller/ContactController.php
  src/Model/CatManager.php
  src/View/Contact/index.html.twig
  src/View/Home/index.html.twig
  src/routes.php
Labels: Reviewed

#132 S2 us32 cats page
  .gitignore
  src/View/Cats/_card.html.twig
  src/View/Cats/_cats-banner.html.twig
  src/View/Cats/index.html.twig
Labels: Reviewed, Corrections done, Conflicts

#125 S02 us19 create editing form
  public/assets/css/edit-admin.css
  public/assets/css/style-admin.css
  public/assets/images/return.svg
  src/Controller/AdminActualityController.php
  src/Controller/AdminCatController.php
  src/Model/AdminBreedManager.php
  src/Model/AdminColorManager.php
  src/Model/AdminFurrManager.php
  src/Model/AdminGenderManager.php
  src/Model/CatManager.php
  src/View/Admin/Cat/_banner.html.twig
  src/View/Admin/Cat/_form.html.twig
  src/View/Admin/Cat/edit.html.twig
  src/View/Cat/_large-card.html.twig
  src/View/layoutAdmin.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#140 S02 us19 2 upload image / us18 delete admin
  public/assets/css/edit-admin.css
  src/Controller/AdminCatController.php
  src/Model/CatManager.php
  src/View/Admin/Cat/_form.html.twig
  src/routes.php
Labels: Reviewed

#127 creation members cards
  database.sql
  public/assets/css/asso.css
  public/assets/css/style.css
  public/assets/images/silhouette.png
  src/Controller/AssociationController.php
  src/Model/MemberManager.php
  src/View/Association/_card.html.twig
  src/View/Association/index.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#134 réduction icônes et taille de police
  public/assets/css/admin-actuality.css
  public/assets/css/style-admin.css
  src/Controller/AdminActualityController.php
  src/View/Admin/Actuality/index.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#142 FIX_US15
  src/Model/CatManager.php
  src/Model/ContactManager.php
  src/View/Contact/index.html.twig
Labels: Reviewed

#144 Fixe page accueil
  public/assets/css/actuality.css
  public/assets/css/banner.css
  public/assets/css/cards.css
  public/assets/css/cats.css
  public/assets/css/large-card.css
  public/assets/images/separator.svg
  src/View/Home/_actualityBanner.html.twig
  src/View/Home/_cardLatestAdopted.html.twig
  src/View/Home/_latestAdoptions.html.twig
  src/View/Home/_toAdopt.html.twig
  src/View/Home/index.html.twig
  src/View/_banner.html.twig
Labels: Reviewed

#143 added button adopt-me and displayed auto-message in form
  public/assets/css/large-card.css
  src/Controller/ContactController.php
  src/View/Cat/_large-card.html.twig
  src/View/Contact/index.html.twig
Labels: Reviewed, Corrections done

#139 S02 us24 delete actuality
  public/assets/css/admin-actuality.css
  public/assets/css/style-admin.css
  src/Controller/AdminActualityController.php
  src/View/Admin/Actuality/index.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#145 FIX_S02US12
  src/View/Association/index.html.twig
Labels: Reviewed

#146 delete accent
  src/View/Admin/Actuality/index.html.twig
Labels: Reviewed

#149 fixed images sizes for members cards
  public/assets/css/asso.css
  src/View/Association/_card.html.twig
Labels: Reviewed

#152 S02 us08 create filter cat page
  public/assets/css/catsFilter.css
  src/Controller/CatController.php
  src/Model/CatManager.php
  src/Model/GenderManager.php
  src/View/Cats/_card.html.twig
  src/View/Cats/_catsFilter.html.twig
  src/View/Cats/index.html.twig
Labels: Reviewed

#154 FIX_US12
  public/assets/css/asso.css
  src/View/Association/_banner-association.html.twig
  src/View/Association/index.html.twig
  src/View/_banner.html.twig
Labels: Reviewed

#156 Fix accents
  src/View/Admin/Actuality/_form.html.twig
  src/View/Admin/Actuality/index.html.twig
Labels: Reviewed

#157 S02 us16 add cats
  src/Controller/AdminCatController.php
  src/Model/CatManager.php
  src/View/Admin/Cat/add.html.twig
  src/routes.php
Labels: Reviewed

#151 FIX_US15
  public/assets/css/form.css
  src/View/Contact/index.html.twig
Labels: Reviewed

#158 Fix banner Home
  src/View/Association/_banner-association.html.twig
  src/View/_banner.html.twig
Labels: Reviewed

#169 placeholders added
  public/assets/images/cat-profil.svg
  src/View/Admin/Cat/_banner.html.twig
  src/View/Cat/_large-card.html.twig
  src/View/Cats/_card.html.twig
  src/View/Home/_cardLatestAdopted.html.twig
  src/View/Home/_cardToAdopt.html.twig
Labels: Reviewed

#172 S02US17 cat admin page
  public/assets/css/adminCats.css
  src/Controller/AdminCatController.php
  src/View/Admin/Cat/index.html.twig
  src/routes.php
Labels: Reviewed

#173 S02 us25 1 add image
  database.sql
  public/assets/css/actuality.css
  public/assets/css/banner.css
  src/Controller/AdminActualityController.php
  src/Model/ActualityManager.php
  src/View/Actualities/index.html.twig
  src/View/Admin/Actuality/_form.html.twig
Labels: Reviewed

#175 Fix select default value admin add cats
  src/View/Admin/Cat/_form.html.twig
Labels: Reviewed, FIX

#176 FIX-US15 remove paw responsive
  src/View/Contact/index.html.twig
Labels: Reviewed, FIX

#181 add a target blank to facebook logo
  src/View/Item/_footer.html.twig
Labels: Reviewed, FIX

#178 stylisation même taille et espacement
  public/assets/css/banner.css
  src/View/Association/_banner-association.html.twig
  src/View/Association/index.html.twig
  src/View/Cats/_cats-banner.html.twig
  src/View/Contact/_banner-contact.html.twig
  src/View/Contact/index.html.twig
Labels: Reviewed, Corrections done, FIX

#183 delete image upload
  src/Controller/AdminActualityController.php
Labels: Reviewed

#184 added adopted stamp on card for adopted cat
  public/assets/css/cards.css
  public/assets/images/adopted.png
  src/View/Admin/Cat/edit.html.twig
  src/View/Cats/_card.html.twig
Labels: Reviewed

#180 trying to fix missing members cards
  src/View/Association/_banner-association.html.twig
  src/View/Association/_card.html.twig
  src/View/Association/index.html.twig
Labels: Reviewed, FIX

#182 FIX-US15 Textarea modification
  src/View/Contact/index.html.twig
Labels: Reviewed, FIX

#185 added udapte image and placeholder for no image
  public/assets/images/newspaper-mini.svg
  public/assets/images/newspaper-placeholder.svg
  public/assets/images/newspaper.tmp.svg
  src/Controller/AdminActualityController.php
  src/Model/ActualityManager.php
  src/View/Actualities/index.html.twig
  src/View/Admin/Cat/edit.html.twig
Labels: Reviewed, Corrections done, FIX

#188 add the admin part for association members
  public/assets/css/admin-members.css
  src/Controller/AdminAssociationController.php
  src/View/Admin/Association/index.html.twig
  src/View/Item/_footer.html.twig
  src/routes.php
Labels: Reviewed

#190 Done again add form member URGENT
  src/Controller/AdminAssociationController.php
  src/Model/MemberManager.php
  src/View/Admin/Actuality/add.html.twig
  src/View/Admin/Association/_form.html.twig
  src/View/Admin/Association/add.html.twig
  src/View/Admin/Association/index.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#192 added entries to the database
  database.sql
Labels: Reviewed

#191 Fix contact page
  public/assets/css/form.css
  public/assets/images/adress.png
  public/assets/images/phone.png
  src/View/Contact/index.html.twig
Labels: Reviewed, Corrections done, FIX

#194 delete button
  src/View/Admin/Association/index.html.twig
  src/View/Association/_card.html.twig
Labels: Reviewed, FIX

#195 Fix crud design
  public/assets/css/admin-show.css
  src/View/Admin/Actuality/index.html.twig
  src/View/Admin/Actuality/index.html2.twig
  src/View/Admin/Association/index.html.twig
  src/View/Admin/Cat/add.html.twig
  src/View/Admin/Cat/index.html.twig
Labels: Reviewed, FIX

#198 Fix separator end page
  src/View/Association/_banner-association.html.twig
  src/View/Association/_card.html.twig
  src/View/Cats/_card.html.twig
  src/View/Cats/_catsFilter.html.twig
  src/View/Home/_cardLatestAdopted.html.twig
Labels: Reviewed, FIX

#199 add missing link and fix wrong link
  public/assets/css/navbar.css
  public/assets/images/profil.svg
  src/View/Admin/Association/index.html.twig
  src/View/Item/_navbarAdmin.html.twig
  src/routes.php
Labels: Reviewed, FIX

#220 Fix titles missing
  src/View/Actualities/index.html.twig
  src/View/Admin/Actuality/index.html.twig
  src/View/Admin/Association/index.html.twig
  src/View/Admin/Cat/index.html.twig
  src/View/Association/index.html.twig
  src/View/Cat/show.html.twig
  src/View/Cats/index.html.twig
  src/View/Contact/index.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed, FIX

#221 Fix actualities in navbar
  public/assets/css/navbar.css
  public/assets/images/newspaperNavbar.svg
  src/View/Item/_navbar.html.twig
  src/View/Item/_navbarAdmin.html.twig
Labels: Reviewed, Corrections done, FIX

#224 change the image for the image holder of members cards
  src/View/Association/_card.html.twig
Labels: Reviewed, FIX

#225 Fix edit button
  src/View/Admin/Actuality/index.html.twig
  src/View/Admin/Cat/index.html.twig
Labels: Reviewed, FIX

#227 Fix logo cat page mobile
  src/View/Item/_navbar.html.twig
Labels: Reviewed, FIX

#229 fix issue when submit no image, previous image was deleted
  src/Controller/AdminActualityController.php
  src/Controller/AdminCatController.php
  src/View/Admin/Actuality/add.html.twig
Labels: Reviewed, FIX

#226 Fix admin add
  public/assets/css/admin-actuality.css
  public/assets/css/form.css
  src/View/Admin/Actuality/add.html.twig
  src/View/Admin/Actuality/edit.html.twig
  src/View/Admin/Actuality/index.html.twig
  src/View/Admin/Actuality/index.html2.twig
  src/View/Contact/index.html.twig
Labels: Reviewed, Corrections done, FIX

#231 Fix us15 map
  src/View/Contact/index.html.twig
Labels: Reviewed, FIX

#236 Fix admin ban
  src/View/Admin/Actuality/edit.html.twig
  src/View/Admin/Actuality/index.html.twig
  src/View/Admin/Association/index.html.twig
  src/View/Admin/Cat/edit.html.twig
  src/View/Admin/Cat/index.html.twig
Labels: Reviewed, FIX

#235 Fix footer mention legale
  src/View/Contact/index.html.twig
  src/View/Item/_footer.html.twig
Labels: Reviewed, FIX

#237 padding form
  src/View/Contact/index.html.twig
Labels: Reviewed, FIX

#238 fix favicon
  public/assets/images/favicon.png
Labels: Reviewed, FIX

#240 Fix us15 spelling issue
  src/View/Contact/index.html.twig
Labels: Reviewed, FIX

#241 fix all the buttons looks the same
  public/assets/css/admin-show.css
  src/View/Admin/Actuality/index.html.twig
  src/View/Admin/Association/index.html.twig
  src/View/Admin/Cat/index.html.twig
Labels: Reviewed, FIX

#242 Fix unlink
  src/Controller/AdminActualityController.php
  src/Controller/AdminCatController.php
Labels: Reviewed, FIX

#243 fix card_cat issues
  src/View/Cat/_large-card.html.twig
  src/View/Cats/_card.html.twig
Labels: Reviewed, FIX

#245 fixed order alphabetically
  src/Controller/AdminCatController.php
Labels: Reviewed, FIX

#246 modification
  src/Controller/AdminActualityController.php
  src/View/Admin/Actuality/index.html.twig
Labels: Reviewed, FIX

#248 change members cards
  src/View/Association/_card.html.twig
Labels: Reviewed, FIX

#249 fixed
  src/View/Admin/Actuality/index.html.twig
Labels: Reviewed, FIX

#244 Admin fixes
  public/assets/css/style.css
  src/Controller/AdminAssociationController.php
  src/Controller/AdminCatController.php
  src/View/Admin/Association/_form.html.twig
  src/View/Cat/_cat-banner.html.twig
  src/View/Cat/_large-card.html.twig
  src/View/Cat/show.html.twig
  src/View/Cats/_card.html.twig
  src/View/Cats/_catsFilter.html.twig
  src/View/Home/_cardLatestAdopted.html.twig
  src/View/Item/_navbarAdmin.html.twig
Labels: Reviewed, FIX

#250 C'est la fin
  public/assets/css/admin-actuality-form.css
  public/assets/css/admin-actuality.css
  public/assets/css/admin-show.css
  public/assets/css/form.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/favicon.png
  public/assets/images/newspaperNavbar.svg
  public/assets/images/profil.svg
  src/Controller/AdminActualityController.php
  src/Controller/AdminAssociationController.php
  src/Controller/AdminCatController.php
  src/View/Actualities/index.html.twig
  src/View/Admin/Actuality/add.html.twig
  src/View/Admin/Actuality/edit.html.twig
  src/View/Admin/Actuality/index.html.twig
  src/View/Admin/Association/_form.html.twig
  src/View/Admin/Association/index.html.twig
  src/View/Admin/Cat/_form.html.twig
  src/View/Admin/Cat/add.html.twig
  src/View/Admin/Cat/edit.html.twig
  src/View/Admin/Cat/index.html.twig
  src/View/Association/_banner-association.html.twig
  src/View/Association/_card.html.twig
  src/View/Association/index.html.twig
  src/View/Cat/_cat-banner.html.twig
  src/View/Cat/_large-card.html.twig
  src/View/Cat/show.html.twig
  src/View/Cats/_card.html.twig
  src/View/Cats/_catsFilter.html.twig
  src/View/Cats/index.html.twig
  src/View/Contact/index.html.twig
  src/View/Home/_cardLatestAdopted.html.twig
  src/View/Home/index.html.twig
  src/View/Item/_footer.html.twig
  src/View/Item/_navbar.html.twig
  src/View/Item/_navbarAdmin.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed
